[features]
seeds = false
[programs.devnet]
cashier = "GH6SLYoAS6D2Vq2UJGQ3bGDCLma9n2fi61X4VtgLozq7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/tomekregulski/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
